import { AzureBase } from "./AzureBase";

export interface PrivateEndpoint extends AzureBase {
    ResourceId: string;
    Id: string;
    Identity?: null;
    Kind: string;
    Location: string;
    ManagedBy?: null;
    ResourceName: string;
    Name: string;
    ExtensionResourceName?: null;
    ParentResource?: null;
    Plan?: null;
    Properties: Properties;
    ResourceGroupName: string;
    Type: string;
    ResourceType: string;
    ExtensionResourceType?: null;
    TagsTable: string;
    SubscriptionId: string;
    CreatedTime?: null;
    ChangedTime?: null;
    ETag?: null;
}
  
interface Properties {
    serverFarmId: number;
    name: string;
    workerSize: string;
    workerSizeId: number;
    workerTierName?: null;
    numberOfWorkers: number;
    currentWorkerSize: string;
    currentWorkerSizeId: number;
    currentNumberOfWorkers: number;
    status: string;
    webSpace: string;
    subscription: string;
    adminSiteName?: null;
    hostingEnvironment?: null;
    hostingEnvironmentProfile?: null;
    maximumNumberOfWorkers: number;
    planName: string;
    adminRuntimeSiteName?: null;
    computeMode: string;
    siteMode?: null;
    geoRegion: string;
    perSiteScaling: boolean;
    elasticScaleEnabled: boolean;
    maximumElasticWorkerCount: number;
    numberOfSites: number;
    hostingEnvironmentId?: null;
    isSpot: boolean;
    spotExpirationTime?: null;
    freeOfferExpirationTime?: null;
    tags: AzureBase["Tags"];
    kind: string;
    resourceGroup: string;
    reserved: boolean;
    isXenon: boolean;
    hyperV: boolean;
    mdmId: string;
    targetWorkerCount: number;
    targetWorkerSizeId: number;
    provisioningState: string;
    webSiteId?: null;
    existingServerFarmIds?: null;
    kubeEnvironmentProfile?: null;
    zoneRedundant: boolean;
}
